version: '2'
services:
  nodejs:
    build: .
    command: node index.js
    restart: always
    volumes:
      - ./:/app:delegated
      - /app/node_modules
    ports:
      - '8080:8080'

  postgres:
    image: postgres:13.3
    restart: always
    environment:
      POSTGRES_PASSWORD: "qweasdzxcPOI09"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ../postgresql/data:/var/lib/postgresql/data
    ports:
      - '5433:5432'