version: '2'
services:
  react-app:
    build: ./app
    command: npm start
    volumes:
      - ./app/:/app:delegated
      - /app/node_modules
    ports:
      - '3000:3000'

  # postgres:
  #  image: postgres:13.3
  #  restart: always
  #  environment:
  #     POSTGRES_PASSWORD: "qweasdzxcPOI09"
  #     PGDATA: "/var/lib/postgresql/data/pgdata"
  #  volumes:
  #     - ../postgresql/data:/var/lib/postgresql/data
  #  ports:
  #     - '5433:5432'